class ZCX_TBOX_CSVMAN definition
  public
  inheriting from CX_STATIC_CHECK
  final
  create public .

public section.

  constants ZCX_TBOX_CSVMAN type SOTR_CONC value '00155DDCB56F1EEDB3CD4A4C933A527D' ##NO_TEXT.
  constants INVALID_TABLE type SOTR_CONC value '00155DDCB56F1EEDB3CCE751CC8D9242' ##NO_TEXT.
  constants INVALID_DELIM_QUOTE type SOTR_CONC value '00155DDCB56F1EEDB3CE2CBB4A7C5306' ##NO_TEXT.
  constants INVALID_DELIM_ESCAPE type SOTR_CONC value '00155DDCB56F1EEDB3CE2CBB4A7C7306' ##NO_TEXT.
  constants INVALID_ESCAPE_QUOTE type SOTR_CONC value '00155DDCB56F1EEDB3CE2CBB4A7C9306' ##NO_TEXT.
  constants QUOTECHAR_DOUBLE type SOTR_CONC value '00155DDCB56F1EEDB3CE30A1422C5307' ##NO_TEXT.
  constants QUOTECHAR_QUOTING type SOTR_CONC value '00155DDCB56F1EEDB3CE30A1422C7307' ##NO_TEXT.
  data METHOD_NAME type SEOCMPNAME .
  data SAP_VALUE type STRING .

  methods CONSTRUCTOR
    importing
      !TEXTID like TEXTID optional
      !PREVIOUS like PREVIOUS optional
      !METHOD_NAME type SEOCMPNAME optional
      !SAP_VALUE type STRING optional .
protected section.
private section.
ENDCLASS.



CLASS ZCX_TBOX_CSVMAN IMPLEMENTATION.


  method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
TEXTID = TEXTID
PREVIOUS = PREVIOUS
.
 IF textid IS INITIAL.
   me->textid = ZCX_TBOX_CSVMAN .
 ENDIF.
me->METHOD_NAME = METHOD_NAME .
me->SAP_VALUE = SAP_VALUE .
  endmethod.
ENDCLASS.
